---
title: "Movielens"
output:
  html_document:
    number_sections: yes
    toc: yes
    toc_depth: 3
  pdf_document:
    toc: yes
    toc_depth: '3'
date: "`r Sys.time()`"
---

```{r setup, include=FALSE}
library(scales)
library(tidyverse)
library(knitr)

# set plot theme
theme_set(theme_bw())
```

# Load and preview data

Read data from the `ratings.csv` file
```{r load-data}
ratings <- read_csv('ratings.csv',
                    col_names = c('user_id','movie_id','rating','timestamp'))
```

Loaded `r format(object.size(ratings), units="Mb")` of ratings data, containing `r format(nrow(ratings), big.mark = ",")` ratings. Here's a preview:
```{r preview-data}
head(ratings) %>% kable()
```

# Summary statistics

```{r dist-ratings}
# plot the distribution of rating values https://speakerdeck.com/jhofman/modeling-social-data-lecture-2-introduction-to-counting?slide=26

ggplot(ratings,aes(x=rating))+
  geom_bar()+
  scale_y_continuous(label = comma)+
  xlab('Rating') +
  ylab('Number of Ratings')
```

## Per-movie stats

```{r aggregate-by-movie}
# aggregate ratings by movie, computing mean and number of ratings
# hint: use the n() function for easy counting within a group

rating_mean_num <- ratings %>% 
  group_by(movie_id) %>% 
  summarize(num_rating = n(),
            mean_rating = mean(rating))
rating_mean_num
```

```{r dist-movie-popularity}
# plot distribution of movie popularity (= number of ratings the movie received)
# hint: try scale_x_log10() for a logarithmic x axis

rating_mean_num %>% 
  ggplot(aes(x = num_rating))+
  geom_histogram(bins = 60)+
  scale_x_log10() +
  xlab('Number of ratings') +
  ylab('Number of movies')
```

```{r dist-mean-ratings-by-movie}
# plot distribution of mean ratings by movie https://speakerdeck.com/jhofman/modeling-social-data-lecture-2-introduction-to-counting?slide=28
# hint: try geom_histogram and geom_density
rating_mean_num %>% 
  ggplot(aes(x = mean_rating)) +
  #geom_histogram() +
  geom_density(fill="black")+
  xlab('Mean Rating by Movie') +
  ylab('Density')

```

```{r cdf-movie-pop}
# rank movies by popularity and compute the cdf, or fraction of movies covered by the top-k moves https://speakerdeck.com/jhofman/modeling-social-data-lecture-2-introduction-to-counting?slide=30
# hint: use dplyr's rank and arrange functions, and the base R sum and cumsum functions
# store the result in a new data frame so you can use it in creating figure 2 from the paper below

# plot the CDF of movie popularity

cdf_ratings <- ratings %>%
  group_by(movie_id) %>% 
  summarise(num_rating = n()) %>% 
  arrange(desc(num_rating)) %>% 
  mutate( rank = row_number()) %>% 
  ungroup() %>% 
  mutate(cdf = cumsum(num_rating)/sum(num_rating))

ggplot(cdf_ratings, aes(x=rank, y = cdf))+
  geom_line() +
  scale_y_continuous(label = percent)+
  scale_x_continuous(label = comma) +
  xlab('Movie rank') +
  ylab('Cumulative popularity')
```


# Per-user stats

```{r aggregate-by-user}
# aggregate ratings by user, computing mean and number of ratings

user_rating_mean_num <- ratings %>% 
  group_by(user_id) %>% 
  summarize(num_rating = n(),
            mean_rating = mean(rating))
user_rating_mean_num
```

```{r dist-user-activity}
# plot distribution of user activity (= number of ratings the user made)
# hint: try a log scale here
user_rating_mean_num %>% 
  ggplot(aes(x = num_rating))+
  geom_histogram(bins = 60)+
  scale_x_log10()+
  xlab('Number of rating the user made')+
  ylab('Number of Users')


```

# Anatomy of the long tail

```{r long-tail}
# generate the equivalent of figure 2 of this paper:
# https://5harad.com/papers/long_tail.pdf

# Specifically, for the subset of users who rated at least 10 movies,
# produce a plot that shows the fraction of users satisfied (vertical
# axis) as a function of inventory size (horizontal axis). We will
# define "satisfied" as follows: an individual user is satisfied p% of
# the time at inventory of size k if at least p% of the movies they
# rated are contained in the top k most popular movies. As in the
# paper, produce one curve for the 100% user satisfaction level and
# another for 90%---do not, however, bother implementing the null
# model (shown in the dashed lines).

# get rank for each distinct movie
movie_rank <- ratings %>%
  group_by(movie_id) %>% 
  summarise(num_rating = n()) %>% 
  arrange(desc(num_rating)) %>% 
  mutate( rank = row_number()) %>% 
  select(movie_id, rank)

# get user_id and movie_id
users <- ratings %>% 
  select(user_id,movie_id)

#combine movie rank with user_id and movie_id
user_with_movie_rank<-left_join(movie_rank,users, by="movie_id")


# get cdf for 100% satisfaction 
# note to myself: if you don't understand the code again, use View to see the data at each step
user_max_rank <- user_with_movie_rank %>% 
  group_by(user_id) %>% 
  summarise(max_rank = max(rank)) %>% 
  arrange(max_rank) %>% 
  select(user_id, max_rank) %>% 
  group_by(max_rank) %>% 
  summarise(count = n()) %>% 
  mutate(cdf100 = cumsum(count)/sum(count),
         label = "100% satisfaction")


# get cdf for 90% satisfaction 
user_90_rank <- user_with_movie_rank %>% 
  group_by(user_id) %>% 
  summarise(rank_90 = quantile(rank,0.9)) %>%
  arrange(rank_90) %>%
  select(user_id, rank_90) %>%
  group_by(rank_90) %>%
  summarise(count = n()) %>%
  mutate(cdf90 = cumsum(count)/sum(count),
         label = "90% satisfaction")


# combine data for plotting
label <- c(user_max_rank$label, user_90_rank$label)
y <- c(user_max_rank$cdf100,user_90_rank$cdf90)
x <- c(user_max_rank$max_rank ,user_90_rank$rank_90)

plot_data <- data.frame(label, x, y)

plot_data %>% 
  group_by(label) %>% 
  ggplot(aes(x=x, y=y, color = label)) +
  geom_line()+
  scale_y_continuous(label = percent)+
  scale_x_continuous(label = comma) +
  xlab('Inventory Size') +
  ylab('Percent of Users Satisfied')


# plot separate graphs

# ggplot(user_max_rank, aes(x=max_rank, y = cdf100))+
#   geom_line() +
#   scale_y_continuous(label = percent)+
#   scale_x_continuous(label = comma) +
#   xlab('Inventory Size') +
#   ylab('Percent of Users Satisfied(100%)')
# 
# 
# 
# ggplot(user_90_rank, aes(x=rank_90, y = cdf90))+
#   geom_line() +
  # scale_y_continuous(label = percent)+
  # scale_x_continuous(label = comma) +
  # xlab('Inventory Size') +
  # ylab('Percent of Users Satisfied(90%)')

```
